version: "3.9"

services:
  db:
    image: 'postgres:15.1-alpine3.17'
    restart: unless-stopped
    ports:
      - 6000:5432
    # Persist db data in a volume
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    env_file:
      - .env.local
