name: Deploy RP

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      run: |
        git checkout master
        git pull
      working-directory: /home/pi2/Web/basic-workout-tracker
    - name: Run Deploy Script
      run: |
       chmod +x deploy.sh
       ./deploy.sh
