name: Lint

on:
  push:
    branches:
      - development
      - staging
      - production
      - master

env:
  NODE_VERSION: 18

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd ./next-app
          npm ci

      - name: Code Linting
        run: |
          cd ./next-app
          npm run lint
